import java.io.IOException;
import java.sql.* ;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;

/**
 * Servlet implementation class for Servlet: ConfigurationTest
 *
 */
public class Editor extends HttpServlet {
    /**
     * The Servlet constructor
     * 
     * @see javax.servlet.http.HttpServlet#HttpServlet()
     */
    public Editor() {}

    public static String username = "CS144";
    public static String password = "";
    private PreparedStatement retrievedStmt = null;
    private PreparedStatement postStmt = null;

    public void init() throws ServletException
    {
        /*  write any servlet initialization code here or remove this function */
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection (
                "jdbc:mysql://localhost:3306/DatabaseName", username, password
                );
      retrievedStmt = con.prepareStatement(
                "SELECT * FROM Posts where username = ? and postid = ?"
                );

        } catch(SQLException ex) {
            return;
        }
    }
    
    public void destroy()
    {
        /*  write any servlet cleanup code here or remove this function */
    }

    /**
     * Handles HTTP GET requests
     * 
     * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your GET method handling code here
	// currently we simply show the page generated by "edit.jsp"

    // retrieve parameter vales
        String action = request.getParameter("action");
        String username = request.getParameter("username");
        String post_id = request.getParameter("postid");
        String title = request.getParameter("title");
        String body = request.getParameter("body");
        int postid = (post_id == null) ? 0 : Integer.parseInt(post_id);
        //handles open, preview, list
        switch (action) {
            case "open":
                Post post = retrievePost(username, postid);
                request.setAttribute("title", post.title);
                request.setAttribute("body", post.body);
                request.getRequestDispatcher("/edit.jsp").forward(request, response);

            case "preview":
            case "list":

        }
        //request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }
    
    /**
     * Handles HTTP POST requests
     * 
     * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your POST method handling code here
	// currently we simply show the page generated by "edit.jsp"
        request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }

    // retrieve single post from DB with known username and postid
    class retrievePost(String username, int postid) 
       //throws ServletException, IOException ,ClassNotFoundException,SQLException
       {
        Post post = null;
        retrievedStmt.setString(1, username);
        retrievedStmt.setInt(2, postid);
        ResultSet rs = retrievedStmt.executeQuery();
        while (rs.next()) {
            post = new Post(rs.getString("username"), rs.getInt("postid"), rs.getString("title"), rs.getString("body"));
        }
        return post;
    }


}

