import java.io.IOException;
import java.sql.* ;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;

/**
 * Servlet implementation class for Servlet: ConfigurationTest
 *
 */

public class Editor extends HttpServlet {
    /**
     * The Servlet constructor
     * 
     * @see javax.servlet.http.HttpServlet#HttpServlet()
     */
    public Editor() {}

    public static String username = "cs144";
    public static String password = "";
    private PreparedStatement retrievedStmt = null;
    private PreparedStatement postStmt = null;

    public void init() throws ServletException
    {
        /*  write any servlet initialization code here or remove this function */
<<<<<<< HEAD
        // try {
        //     Class.forName("com.mysql.jdbc.Driver");
        //     Connection con = null;
        //     con = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", "");
        //     retrievedStmt = con.prepareStatament(
        //         "SELECT * FROM Posts where username = ? and postid = ?"
        //         );

        // } catch(SQLException ex) {
        //     return;
        // }
         /* load the driver */
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            return;
        }
    
        Connection c = null;
        Statement  s = null; 
        ResultSet rs = null; 

        try {
            String body,username ;
            float price ;
    
            /* create an instance of a Connection object */
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", ""); 
            
            /* You can think of a JDBC Statement object as a channel
            sitting on a connection, and passing one or more of your
            SQL statements (which you ask it to execute) to the DBMS*/

            s = c.createStatement() ;

            //s.executeUpdate("DROP TABLE IF EXISTS Sells" ) ;
            //s.executeUpdate("CREATE TABLE Sells(bar VARCHAR(40), beer VARCHAR(40), price REAL)" ) ;
            //s.executeUpdate("INSERT INTO Sells VALUES('Bar Of Foo', 'BudLite', 2.00)") ;

            // rs = s.executeQuery("SELECT body FROM Posts") ;
            // while( rs.next() ){
            //      body = rs.getString("body");
            //      username = rs.getString("username");
            //      System.out.println("Doesthis work" + body +"for" + username);
            // }
           retrievedStmt = c.prepareStatement(
                "SELECT * FROM Posts where username = ? and postid = ?"
            );
        } catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        } 
=======
        /*try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection (
                "jdbc:mysql://localhost:3306/DatabaseName", username, password
                );
            retrievedStmt = con.prepareStatament(
                "SELECT * FROM Posts"
                );

        } catch(SQLException ex) {
            return;
        }*/
>>>>>>> 19b6c8ce64f6d76e83989ac98a8d4597483dcc7d
    }
    
    public void destroy()
    {
        /*  write any servlet cleanup code here or remove this function */
    }

    /**
     * Handles HTTP GET requests
     * 
     * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException
    {
	// implement your GET method handling code here
	// currently we simply show the page generated by "edit.jsp"
<<<<<<< HEAD
=======
        /* load the driver */
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            return;
        }
    
        Connection c = null;
        Statement  s = null; 
        ResultSet rs = null; 

        try {
            String body,username ;
            float price ;
    
            /* create an instance of a Connection object */
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", ""); 
            
            /* You can think of a JDBC Statement object as a channel
            sitting on a connection, and passing one or more of your
            SQL statements (which you ask it to execute) to the DBMS*/

            s = c.createStatement() ;

            //s.executeUpdate("DROP TABLE IF EXISTS Sells" ) ;
            //s.executeUpdate("CREATE TABLE Sells(bar VARCHAR(40), beer VARCHAR(40), price REAL)" ) ;
            //s.executeUpdate("INSERT INTO Sells VALUES('Bar Of Foo', 'BudLite', 2.00)") ;

            rs = s.executeQuery("SELECT body FROM Posts") ;
            while( rs.next() ){
                 body = rs.getString("body");
                 username = rs.getString("username");
                 request.setAttribute("body", body);
                 //System.out.println("Doesthis work" + body +"for" + username);
            }
        } catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        } finally {
            try { rs.close(); } catch (Exception e) { /* ignored */ }
            try { s.close(); } catch (Exception e) { /* ignored */ }
            try { c.close(); } catch (Exception e) { /* ignored */ }
        }
    }
>>>>>>> 19b6c8ce64f6d76e83989ac98a8d4597483dcc7d
    // retrieve parameter vales
        /*String action = request.getParameter("action");
        String username = request.getParameter("username");
        String post_id = request.getParameter("postid");
        String title = request.getParameter("title");
        String body = request.getParameter("body");
        int postid = (post_id == null) ? 0 : Integer.parseInt(post_id);
        //handles open, preview, list
        switch (action) {
            case "open":
                try {
                    Post post = retrievePost(username, postid);
                    request.setAttribute("title", post.title);
                    request.setAttribute("body", post.body);
                } catch (SQLException ex){
                System.out.println("SQLException caught");
                System.out.println("---");
                while ( ex != null ) {
                    System.out.println("Message   : " + ex.getMessage());
                    System.out.println("SQLState  : " + ex.getSQLState());
                    System.out.println("ErrorCode : " + ex.getErrorCode());
                    System.out.println("---");
                    ex = ex.getNextException();
            }
        } 
                request.getRequestDispatcher("/edit.jsp").forward(request, response);

<<<<<<< HEAD
            // case "preview":
            // case "list":
            default:
                return;

        }
        // request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }
=======
            case "preview":
            case "list": */
        //request.getRequestDispatcher("/edit.jsp").forward(request, response);
    
        //}
    
>>>>>>> 19b6c8ce64f6d76e83989ac98a8d4597483dcc7d
    
    /**
     * Handles HTTP POST requests
     * 
     * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your POST method handling code here
	// currently we simply show the page generated by "edit.jsp"
        request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }

    // retrieve single post from DB with known username and postid
<<<<<<< HEAD
    Post retrievePost(String username, int postid) throws SQLException{
=======
    /*Post retrievePost(String username, int postid) {
>>>>>>> 19b6c8ce64f6d76e83989ac98a8d4597483dcc7d
        Post post = null;
        try{
            retrievedStmt.setString(1, username);
            retrievedStmt.setInt(2, postid);
            ResultSet rs = retrievedStmt.executeQuery();
            while (rs.next()) {
                post = new Post(rs.getString("username"), rs.getInt("postid"), rs.getString("title"), rs.getString("body"));
            }
        } catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        } 
        return post;
    }*/


}

