import java.io.IOException;
import java.sql.* ;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.servlet.Servlet;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.sql.DataSource;

import org.commonmark.node.*;
import org.commonmark.parser.Parser;
import org.commonmark.renderer.html.HtmlRenderer;

/**
 * Servlet implementation class for Servlet: ConfigurationTest
 *
 */
public class Editor extends HttpServlet {
    /**
     * The Servlet constructor
     * 
     * @see javax.servlet.http.HttpServlet#HttpServlet()
     */
    public Editor() {}

    public static String username = "CS144";
    public static String password = "";
    private PreparedStatement retrievedStmt = null;
    private PreparedStatement postStmt = null;
    private PreparedStatement updateStmt = null;
    private int maxid = 0;

    public void init() throws ServletException
    {
        /*  write any servlet initialization code here or remove this function */
        // try {
        //     Class.forName("com.mysql.jdbc.Driver");
        // } catch (ClassNotFoundException ex) {
        //     System.out.println(ex);
        //     return;
        // }
    
        // Connection c = null;
        // Statement  s = null; 
        // ResultSet rs = null; 

        // try {
        //     /* create an instance of a Connection object */
        //     c = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", ""); 
        //     retrievedStmt = c.prepareStatement(
        //         "SELECT * FROM Posts where username = ? and postid = ?"
        //     );
        //     postStmt = c.prepareStatement(
        //         "INSERT INTO Posts (username, postid, title, body, modified, created) VALUES (?, ?, ?, ?, ?, ?)"
        //     );
        //     updateStmt = c.prepareStatement(
        //         "UPDATE Posts SET title = ?, body = ?, modified = ? WHERE username = ? AND postid = ?"
        //     );    
        // } catch (SQLException ex){
        //     System.out.println("SQLException caught");
        //     System.out.println("---");
        //     while ( ex != null ) {
        //         System.out.println("Message   : " + ex.getMessage());
        //         System.out.println("SQLState  : " + ex.getSQLState());
        //         System.out.println("ErrorCode : " + ex.getErrorCode());
        //         System.out.println("---");
        //         ex = ex.getNextException();
        //     }
        // }
        
    }
    
    public void destroy()
    {
        /*  write any servlet cleanup code here or remove this function */
    }

    /**
     * Handles HTTP GET requests
     * 
     * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doGet(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your GET method handling code here
	// currently we simply show the page generated by "edit.jsp"

    // retrieve parameter vales
        String action = request.getParameter("action");
        String username = request.getParameter("username");
        String post_id = request.getParameter("postid");
        String title = request.getParameter("title");
        String body = request.getParameter("body");
        int postid = (post_id == null) ? 0 : Integer.parseInt(post_id);
        //handles open, preview, list
        switch (action) {
            case "open":
                Post post = retrievePost(username, postid);
                request.setAttribute("title",post.title);
                request.setAttribute("body", post.body);
                request.setAttribute("username",post.username);
                request.setAttribute("postid", post.postid);
                request.getRequestDispatcher("/edit.jsp").forward(request, response);
                break;

            case "preview":
                break;
            case "list":
                break;
            default:
                System.out.println("ok works");
                request.setAttribute("body", "ok this works");
                request.getRequestDispatcher("/edit.jsp").forward(request, response);

        }
        //request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }
    
    /**
     * Handles HTTP POST requests
     * 
     * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request,
     *      HttpServletResponse response)
     */
    public void doPost(HttpServletRequest request, HttpServletResponse response)
        throws ServletException, IOException 
    {
	// implement your POST method handling code here
	// currently we simply show the page generated by "edit.jsp"
        String action = request.getParameter("action");
        String username = request.getParameter("username");
        String post_id = request.getParameter("postid");
        String title = request.getParameter("title");
        String body = request.getParameter("body");
        int postid = (post_id == null) ? 0 : Integer.parseInt(post_id);
        switch (action) {
            case "save":
                // System.out.println("arrived at save");
                doSave(username, postid, title, body);
                // System.out.println("finished save");
                // request.setAttribute("body", "ok this works2");
                // request.getRequestDispatcher("/edit.jsp").forward(request, response);
                request.setAttribute("username",username);
                request.setAttribute("postid", post_id);
                request.setAttribute("title", title);
                request.setAttribute("body", body);
                request.getRequestDispatcher("/edit.jsp").forward(request, response);

        }
        // request.getRequestDispatcher("/edit.jsp").forward(request, response);
    }

    private static java.sql.Timestamp getCurrentTimeStamp() {
        java.util.Date today = new java.util.Date();
        return new java.sql.Timestamp(today.getTime());
    }

    // retrieve single post from DB with known username and postid
    Post retrievePost(String username, int postid) {
        //--------//
        Post post = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            return post;
        }
    
        Connection c = null;
        Statement  s = null; 

        try {
            /* create an instance of a Connection object */
            c = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", ""); 
            retrievedStmt = c.prepareStatement(
                "SELECT * FROM Posts where username = ? and postid = ?"
            );   
        } catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        } 
        //--------//
        try {
            retrievedStmt.setString(1, username);
            retrievedStmt.setInt(2, postid);
            ResultSet rs = retrievedStmt.executeQuery();
            while (rs.next()) {
                post = new Post(rs.getString("username"), rs.getInt("postid"), rs.getString("title"), rs.getString("body"));
            }
        } catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        }
        return post;
    }

    private void doSave(String username, int postid, String title, String body) { 
        try {
            if (postid <= 0) {//assign new postid, save content as new post
                //--------//
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException ex) {
                    System.out.println(ex);
                    return;
                }
            
                Connection c = null;
                Statement  s = null; 
                ResultSet rs = null; 

                try {
                    /* create an instance of a Connection object */
                    c = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", ""); 
                    postStmt = c.prepareStatement(
                        "INSERT INTO Posts (username, postid, title, body, modified, created) VALUES (?, ?, ?, ?, ?, ?)"
                    );   
                } catch (SQLException ex){
                    System.out.println("SQLException caught");
                    System.out.println("---");
                    while ( ex != null ) {
                        System.out.println("Message   : " + ex.getMessage());
                        System.out.println("SQLState  : " + ex.getSQLState());
                        System.out.println("ErrorCode : " + ex.getErrorCode());
                        System.out.println("---");
                        ex = ex.getNextException();
                    }
                }
                //--------//
                postStmt.setString(1, username);
                postStmt.setInt(2, maxid+1);
                postStmt.setString(3, title);
                postStmt.setString(4, body);
                postStmt.setTimestamp(5, getCurrentTimeStamp());
                postStmt.setTimestamp(6, getCurrentTimeStamp());
                postStmt.executeUpdate();
            } else { //if tuple exists, update data; if not, don't update
                //--------//
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                } catch (ClassNotFoundException ex) {
                    System.out.println(ex);
                    return;
                }

                try {
                    /* create an instance of a Connection object */
                    Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", ""); 
                    retrievedStmt = c.prepareStatement(
                        "SELECT * FROM Posts where username = ? and postid = ?"
                    );   
                } catch (SQLException ex){
                    System.out.println("SQLException caught");
                    System.out.println("---");
                    while ( ex != null ) {
                        System.out.println("Message   : " + ex.getMessage());
                        System.out.println("SQLState  : " + ex.getSQLState());
                        System.out.println("ErrorCode : " + ex.getErrorCode());
                        System.out.println("---");
                        ex = ex.getNextException();
                    }
                }
                //--------//
                retrievedStmt.setString(1, username);
                retrievedStmt.setInt(2, postid);
                ResultSet rs = retrievedStmt.executeQuery();
                if (rs.next()) { // if tuple exists
                    System.out.println("found tuple");
                    //--------//
                    try {
                        Class.forName("com.mysql.jdbc.Driver");
                    } catch (ClassNotFoundException ex) {
                        System.out.println(ex);
                        return;
                    }

                    try {
                        /* create an instance of a Connection object */
                        Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/CS144", "cs144", ""); 
                        updateStmt = c.prepareStatement(
                            "UPDATE Posts SET title = ?, body = ?, modified = ? WHERE username = ? AND postid = ?"
                        );    
                    } catch (SQLException ex){
                        System.out.println("SQLException caught");
                        System.out.println("---");
                        while ( ex != null ) {
                            System.out.println("Message   : " + ex.getMessage());
                            System.out.println("SQLState  : " + ex.getSQLState());
                            System.out.println("ErrorCode : " + ex.getErrorCode());
                            System.out.println("---");
                            ex = ex.getNextException();
                        }
                    }
                    //--------//
                    updateStmt.setString(1, title);
                    updateStmt.setString(2, body);
                    updateStmt.setTimestamp(3, getCurrentTimeStamp());
                    updateStmt.setString(4, username);
                    updateStmt.setInt(5, postid);
                    updateStmt.executeUpdate();
                    System.out.println("executed update");
                }

             }
         } catch (SQLException ex){
            System.out.println("SQLException caught");
            System.out.println("---");
            while ( ex != null ) {
                System.out.println("Message   : " + ex.getMessage());
                System.out.println("SQLState  : " + ex.getSQLState());
                System.out.println("ErrorCode : " + ex.getErrorCode());
                System.out.println("---");
                ex = ex.getNextException();
            }
        }

    }


}

